# Generated by Django 3.2.17 on 2023-02-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='tapa',
        ),
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
