# Generated by Django 3.2.17 on 2023-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230207_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tapa',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
