# Generated by Django 3.2.17 on 2023-02-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_tapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
