# Generated by Django 3.2.17 on 2023-02-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_tapa_post_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagen',
            new_name='tapa',
        ),
    ]
